### ISSUE TITLE
SQL-Related exception on login

### ISSUE THREAD

**Issue by kandril** [eurofurence/Stage-Squirrel#2]
Everytime I try to login on a fresh installation (user was created and activated), I get this in the app-log:
```javascript
SELECT roles_id FROM sq_map_user_to_role WHERE user_id = 1
db error { Error: ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '6/4/2017, 10:32:28 PM' for column 'user_last_login' at row 1
    at Query.Sequence._packetToError (/home/vagrant/Stage-Squirrel/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/home/vagrant/Stage-Squirrel/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/home/vagrant/Stage-Squirrel/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/vagrant/Stage-Squirrel/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/home/vagrant/Stage-Squirrel/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/vagrant/Stage-Squirrel/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
    --------------------
    at Protocol._enqueue (/home/vagrant/Stage-Squirrel/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Connection.query (/home/vagrant/Stage-Squirrel/node_modules/mysql/lib/Connection.js:208:25)
    at Query._callback (/home/vagrant/Stage-Squirrel/config/passport.js:210:50)
    at Query.Sequence.end (/home/vagrant/Stage-Squirrel/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at Query._handleFinalResultPacket (/home/vagrant/Stage-Squirrel/node_modules/mysql/lib/protocol/sequences/Query.js:137:8)
    at Query.EofPacket (/home/vagrant/Stage-Squirrel/node_modules/mysql/lib/protocol/sequences/Query.js:121:8)
    at Protocol._parsePacket (/home/vagrant/Stage-Squirrel/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/vagrant/Stage-Squirrel/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/home/vagrant/Stage-Squirrel/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/vagrant/Stage-Squirrel/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
  code: 'ER_TRUNCATED_WRONG_VALUE',
  errno: 1292,
  sqlState: '22007',
  index: 0 }
/home/vagrant/Stage-Squirrel/node_modules/mysql/lib/protocol/Parser.js:79
        throw err; // Rethrow non-MySQL errors
        ^

Error: ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '6/4/2017, 10:32:28 PM' for column 'user_last_login' at row 1
    at Query.Sequence._packetToError (/home/vagrant/Stage-Squirrel/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/home/vagrant/Stage-Squirrel/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/home/vagrant/Stage-Squirrel/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/vagrant/Stage-Squirrel/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/home/vagrant/Stage-Squirrel/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/vagrant/Stage-Squirrel/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
    --------------------
    at Protocol._enqueue (/home/vagrant/Stage-Squirrel/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Connection.query (/home/vagrant/Stage-Squirrel/node_modules/mysql/lib/Connection.js:208:25)
    at Query._callback (/home/vagrant/Stage-Squirrel/config/passport.js:210:50)
    at Query.Sequence.end (/home/vagrant/Stage-Squirrel/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at Query._handleFinalResultPacket (/home/vagrant/Stage-Squirrel/node_modules/mysql/lib/protocol/sequences/Query.js:137:8)
    at Query.EofPacket (/home/vagrant/Stage-Squirrel/node_modules/mysql/lib/protocol/sequences/Query.js:121:8)
    at Protocol._parsePacket (/home/vagrant/Stage-Squirrel/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/vagrant/Stage-Squirrel/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/home/vagrant/Stage-Squirrel/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/vagrant/Stage-Squirrel/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
```

**Comment by kandril** [comment]
I think, I found the mischief-maker, after debugging through the code a bit. It's [config/passport.js:210](https://github.com/eurofurence/Stage-Squirrel/blob/64e0e883a02172ef6a08e18345a98c7216ad4573/config/passport.js#L210) as it uses
```javascript
.toLocaleString()
```
on the `Date`-Object to generate a `DATETIME` compatible string, which causes errornous results in some cases. Using the ISO date string format `YYYY-MM-DD HH:mm:ss` might work better here.

I suggest using something like your
```javascript
function getTimeJStoSQL(timeString);
```
from [app/routes.js:36-50](https://github.com/eurofurence/Stage-Squirrel/blob/64e0e883a02172ef6a08e18345a98c7216ad4573/app/routes.js#L36-L50) here instead.

**Comment by Zerbix** [comment]
This was old code. Time functions can be found in utils.js now and now we will use these in this case also.
