### ISSUE TITLE
TypeError:/home/stage/Stage-Squirrel/views/home.ejs:80 78 .... when creating survey

### ISSUE THREAD

**Issue by blackfurball** [eurofurence/Stage-Squirrel#22]
When creating a new survey, the error at the bottom is dumped to the users browser.

Steps to reproduce:
Starting from a clean DB, created initial admin account "Furball-Admin" as per readme and added a single Event-manager account "Furball-Eventmanager":

1. Using admin account: Navigate to: Managing -> Conventions
2. Use "Add convention" button
3. Fill in form with random data (and use edit-workaround workaround from https://github.com/eurofurence/Stage-Squirrel/issues/21 )
4. Using Event-manager account: Navigate to Create-Survey 
5. Fill in plausible data
6. Click "create Event" 
7. Get error dump

Observed behavior: Well, errordump
Expected behavior: No errordump ;)

The survey however seams to be correctly created as it is listed in the event-managers "My Surveys" tab.

The logfile for this issue is stored on the prod system in ~/bugfixing/ with the ticket number in the filename

> TypeError: /home/stage/Stage-Squirrel/views/home.ejs:80 78| <% for (block of notifications) { %> 79| <% if (block.type_id != 13 && block.type_id != 15) { %> >> 80| <% 81| var event = null; 82| if (block.event_id) { 83| if (block.type_id < 6) { Cannot read property '1' of undefined at eval (eval at <anonymous> (/home/stage/Stage-Squirrel/node_modules/ejs/lib/ejs.js:237:14), <anonymous>:86:56) at eval (eval at <anonymous> (/home/stage/Stage-Squirrel/node_modules/ejs/lib/ejs.js:237:14), <anonymous>:93:35) at /home/stage/Stage-Squirrel/node_modules/ejs/lib/ejs.js:250:15 at Object.exports.render (/home/stage/Stage-Squirrel/node_modules/ejs/lib/ejs.js:288:13) at View.exports.renderFile [as engine] (/home/stage/Stage-Squirrel/node_modules/ejs/lib/ejs.js:318:20) at View.render (/home/stage/Stage-Squirrel/node_modules/express/lib/view.js:76:8) at Function.app.render (/home/stage/Stage-Squirrel/node_modules/express/lib/application.js:502:10) at ServerResponse.res.render (/home/stage/Stage-Squirrel/node_modules/express/lib/response.js:777:7) at Query._callback (/home/stage/Stage-Squirrel/app/routes/home.js:16:33) at Query.Sequence.end (/home/stage/Stage-Squirrel/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24) at Query._handleFinalResultPacket (/home/stage/Stage-Squirrel/node_modules/mysql/lib/protocol/sequences/Query.js:139:8) at Query.EofPacket (/home/stage/Stage-Squirrel/node_modules/mysql/lib/protocol/sequences/Query.js:123:8) at Protocol._parsePacket (/home/stage/Stage-Squirrel/node_modules/mysql/lib/protocol/Protocol.js:279:23) at Parser.write (/home/stage/Stage-Squirrel/node_modules/mysql/lib/protocol/Parser.js:76:12) at Protocol.write (/home/stage/Stage-Squirrel/node_modules/mysql/lib/protocol/Protocol.js:39:16) at Socket.<anonymous> (/home/stage/Stage-Squirrel/node_modules/mysql/lib/Connection.js:103:28) at emitOne (events.js:96:13) at Socket.emit (events.js:188:7) at readableAddChunk (_stream_readable.js:176:18) at Socket.Readable.push (_stream_readable.js:134:10) at TCP.onread (net.js:547:20)

**Comment by kandril** [comment]
I assume it might be related to what I wrote for #23 and a missing check for an empty string value as parameter for the `event_day` (day of the convention from dropdown) on the `event_details` table

**Comment by blackfurball** [comment]
Just went through this during testing of #23 and #21. Issue still persists - but I think that is the current known status of this issue :)
