### ISSUE TITLE
Exception when registering new (first) user

### ISSUE THREAD

**Issue by Zefiro** [eurofurence/Stage-Squirrel#6]
I started Squirrel for the first time. I got the login screen, I went to the "new user screen", I entered my data and submitted. The user got created in the database, but then node crashed. Please investigate :)
(Node version is 6.11 = latest)

stage@eurofur2:~/Stage-Squirrel$ node server.js
The magic happens on port 9002
INSERT INTO sq_user ( user_mail, user_password, user_name, user_active ) values ('xxx@zefiro.de','$2a$10$SoM3Th1ng/YoUW15hedH3r3Wou1dB3S7uff','Zefiro','0')
[ '3', '13' ]
INSERT INTO sq_map_user_to_role ( user_id, role_id ) values ('1','3')
INSERT INTO sq_map_user_to_role ( user_id, role_id ) values ('1','13')
/home/stage/Stage-Squirrel/node_modules/mysql/lib/protocol/Parser.js:79
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: Cannot read property '0' of undefined
    at Query._callback (/home/stage/Stage-Squirrel/config/passport.js:133:48)
    at Query.Sequence.end (/home/stage/Stage-Squirrel/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at Query.ErrorPacket (/home/stage/Stage-Squirrel/node_modules/mysql/lib/protocol/sequences/Query.js:88:8)
    at Protocol._parsePacket (/home/stage/Stage-Squirrel/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/stage/Stage-Squirrel/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/home/stage/Stage-Squirrel/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/stage/Stage-Squirrel/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)

**Comment by Zefiro** [comment]
Tried it again with the current master (348ebcb3466d909f280741910ae1e1acee897de7)
I do notice that commit  0aaded2bb56ff43d7352ea15acdf24966c9be178 removed the entries in sq_role. This prevents a new user registration, as no roles are available to select - and thus the button press doesn't do anything (not even an error message, as it does with a weak password)

I added the sq_role entries by hand, but then I'm again getting the same exception thrown and node crashed once I submit.

[StageSquirrelException.txt](https://github.com/eurofurence/Stage-Squirrel/files/1083334/StageSquirrelException.txt)
[npm-debug.log.txt](https://github.com/eurofurence/Stage-Squirrel/files/1083333/npm-debug.log.txt)

**Comment by blackfurball** [comment]
Seams to be fixed in one of the last few commits. I tried it several times during testing and didn't encounter a problem when registering the first user
